POSTS = {1: {"title": "House Prices in Darlington", 
             "href": "001_House_Prices_Darlington.html", 
             "libraries": "Pandas, Great_Tables, Matplotlib",
             "date": "2024-02-11",
             "type": "Notebook"},
         2: {"title": "London Weather", 
             "href": "002_London_Weather.html", 
             "libraries": "Polars, Great_Tables",
             "date": "2024-02-18",
             "type": "Notebook"},
         3: {"title": "London Weather Nanoplots", 
             "href": "003_London_Weather_Nanoplots.html",
             "libraries": "Pandas, Great_Tables",
             "date": "2024-03-20",
             "type": "Notebook"},
         4: {"title": "OWID Surface Temperature Anomalies",
             "href": "004_OWID_Surface_Temperature_Anomalies.html",
             "libraries": "Polars, Matplotlib",
             "date": "2024-03-25",
             "type": "Notebook"},
         5: {"title": "Basic Subplots with Matplotlib",
             "href": "005_Basic_Subplots_with_Matplotlib.html",
             "libraries": "Polars, Matplotlib",
             "date": "2024-04-01",
             "type": "Notebook"},
         6: {"title": "Great Tables Commodity Prices",
             "href": "006_Great_Tables_Commodity_Prices.html",
             "libraries": "Pandas, Great_Tables, BeautifulSoup",
             "date": "2024-04-06",
             "type": "Notebook"},
         7: {"title": "Nicer Subplots with Matplotlib",
             "href": "007_Nicer_Subplots_with_Matplotlib.html",
             "libraries": "Polars, Matplotlib",
             "date": "2024-04-09",
             "type": "Notebook"},
         8: {"title": "Matplotlib slope plot with labels",
             "href": "008_Matplotlib_slope_plot_with_labels.html",
             "libraries": "Polars, Matplotlib",
             "date": "2024-04-10",
             "type": "Notebook"},
         9: {"title": "Matplotlib formatting different units on subplots",
             "href": "009_Matplotlib_formatting_different_units_on_subplots.html",
             "libraries": "Polars, Matplotlib",
             "date": "2024-04-12",
             "type": "Notebook"},
         10: {"title": "Dumbbell and Gantt Chart in Matploblib",
              "href": "010_Dumbbell_and_Gantt_Chart_in_Matplotlib.html",
              "libraries": "Pandas, Matplotlib",
              "date": "2024-04-13",
              "type": "Notebook"},
         11: {"title": "Reuters plot recreation with Matplotlib",
              "href": "011_Reuters_plot_recreation_with_Matplotlib.html",
              "libraries": "Pandas, Matplotlib",
              "date": "2024-04-14",
              "type": "Notebook"}
}